// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lglsznnzluzurtkzxiek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnbHN6bm56bHV6dXJ0a3p4aWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTMzOTUsImV4cCI6MjA2Nzg4OTM5NX0.MYN6Bv6J_sCDmv28SquJPKogTpHlSVhIxa8Gy0kNArI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});